[2023-07-02T21:39:18.210+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_dag.run_etl manual__2023-07-02T16:09:14.158663+00:00 [queued]>
[2023-07-02T21:39:18.216+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_dag.run_etl manual__2023-07-02T16:09:14.158663+00:00 [queued]>
[2023-07-02T21:39:18.217+0530] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-02T21:39:18.235+0530] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): run_etl> on 2023-07-02 16:09:14.158663+00:00
[2023-07-02T21:39:18.254+0530] {standard_task_runner.py:57} INFO - Started process 98443 to run task
[2023-07-02T21:39:18.272+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'load_data_dag', 'run_etl', 'manual__2023-07-02T16:09:14.158663+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/load_data_dag.py', '--cfg-path', '/var/folders/1q/9_fjtq3x20g5lbhb24f74l380000gn/T/tmpu112373z']
[2023-07-02T21:39:18.281+0530] {standard_task_runner.py:85} INFO - Job 25: Subtask run_etl
[2023-07-02T21:39:18.333+0530] {task_command.py:410} INFO - Running <TaskInstance: load_data_dag.run_etl manual__2023-07-02T16:09:14.158663+00:00 [running]> on host shubhams-macbook-air.local
[2023-07-02T21:39:18.381+0530] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your-email@example.com' AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='load_data_dag' AIRFLOW_CTX_TASK_ID='run_etl' AIRFLOW_CTX_EXECUTION_DATE='2023-07-02T16:09:14.158663+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-02T16:09:14.158663+00:00'
[2023-07-02T21:39:18.382+0530] {python.py:183} INFO - Done. Returned value was: <coroutine object call_endpoint at 0x13a1a62f0>
[2023-07-02T21:39:18.385+0530] {xcom.py:634} ERROR - Object of type coroutine is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config or make sure to decorate your object with attr.
[2023-07-02T21:39:18.385+0530] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/shubhampriyadarshi/PycharmProjects/PacktAPI/venv/lib/python3.11/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/Users/shubhampriyadarshi/PycharmProjects/PacktAPI/venv/lib/python3.11/site-packages/airflow/serialization/serde.py", line 171, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'coroutine'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shubhampriyadarshi/PycharmProjects/PacktAPI/venv/lib/python3.11/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shubhampriyadarshi/PycharmProjects/PacktAPI/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2354, in xcom_push
    XCom.set(
  File "/Users/shubhampriyadarshi/PycharmProjects/PacktAPI/venv/lib/python3.11/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shubhampriyadarshi/PycharmProjects/PacktAPI/venv/lib/python3.11/site-packages/airflow/models/xcom.py", line 237, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/Users/shubhampriyadarshi/PycharmProjects/PacktAPI/venv/lib/python3.11/site-packages/airflow/models/xcom.py", line 632, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/Users/shubhampriyadarshi/PycharmProjects/PacktAPI/venv/lib/python3.11/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
           ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/Users/shubhampriyadarshi/PycharmProjects/PacktAPI/venv/lib/python3.11/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type coroutine is not JSON serializable
[2023-07-02T21:39:18.393+0530] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=load_data_dag, task_id=run_etl, execution_date=20230702T160914, start_date=20230702T160918, end_date=20230702T160918
[2023-07-02T21:39:18.398+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 25 for task run_etl (Object of type coroutine is not JSON serializable; 98443)
[2023-07-02T21:39:18.418+0530] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-02T21:39:18.427+0530] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
